<?php

return [
    "Apple" => "A crisp and juicy fruit with a slightly sweet and tart flavor.",
    "Apricot" => "A small, yellow-orange fruit with a soft, juicy flesh and a sweet, slightly tart flavor.",
    "Avocado" => "A creamy fruit with a smooth texture and a rich, nutty flavor.",
    "Banana" => "A sweet and creamy fruit with a soft, slightly fibrous texture.",
    "Cantaloupe" => "A sweet and juicy melon with a light orange flesh.",
    "Cherry" => "A small, sweet fruit with a bright red skin and a firm, juicy flesh.",
    "Coconut" => 'A tropical fruit that grows on the coconut palm tree. The fruit contains a hard outer shell, fibrous husk, and a large edible seed, which is the part we commonly refer to as the "coconut." Coconuts are a rich source of fiber, vitamins, and minerals, and are commonly used in cooking and for their health benefits. Coconut oil, water, and milk are also popular products derived from the fruit.',
    "Dragonfruit" => "A tropical fruit with a bright pink skin and a white, juicy flesh with black seeds.",
    "Durian" => 'Durian is a large, spiky fruit with a strong, pungent odor and a rich, creamy texture. It is native to Southeast Asia and is known for its distinct flavor, which is often described as sweet and savory with a hint of bitterness. Some people love its unique taste, while others find it overwhelming. Durian is also rich in nutrients, including vitamins B and C, and is a good source of fiber.',
    'Fig' => 'Figs are sweet, chewy fruits with a unique texture. They are high in fiber and provide several essential nutrients, such as potassium, calcium, and magnesium. They have a sweet, honey-like taste and can be enjoyed fresh, dried, or as a jam or spread.',
    "Grapefruit" => "A large, juicy citrus fruit with a tart, slightly bitter flavor.",
    "Grapes" => "Small, sweet and juicy fruit that come in many different colors, including green, red and purple.",
    "Guava" => "A tropical fruit with a sweet, juicy flesh and a slightly grainy texture.",
    "Honeydew" => "A sweet and juicy melon with a pale green flesh.",
    "Kiwi" => "A small, brown fruit with a fuzzy brown skin and a bright green flesh.",
    "Lemon" => "A tart and acidic citrus fruit with a bright yellow skin.",
    "Lime" => "A small, green citrus fruit with a tart and acidic flavor.",
    "Lychee" => 'Lychee: Lychee is a small, round fruit with a rough, pinkish-red skin and a sweet, juicy flesh. It is native to China but is now grown in many other parts of the world, including Southeast Asia, India, and South Africa. Lychees are usually eaten fresh and are prized for their delicate, floral flavor and juicy texture. They are also a good source of vitamin C and potassium.',
    "Mango" => "A tropical fruit with a sweet, juicy flesh and a tangy flavor.",
    "Orange" => "A round, juicy citrus fruit with a bright orange skin.",
    "Papaya" => "A tropical fruit with a sweet, juicy flesh and a musky flavor.",
    "Passionfruit" => "A small, round fruit with a hard, purple skin and a juicy, tart-sweet flesh with black seeds.",
    "Peach" => "A soft, juicy fruit with a fuzzy skin and a sweet, slightly tart flavor.",
    "Pear" => "A sweet and juicy fruit with a soft, slightly grainy texture.",
    'Persimmon' => 'Persimmons are a sweet and juicy fruit with a unique flavor. They are high in vitamin A and fiber, and also contain antioxidants that may help reduce inflammation and improve heart health. Persimmons can be eaten fresh or cooked and are often used in baked goods and desserts.',
    "Pineapple" => "A tropical fruit with a tough, spiky skin and a sweet, juicy flesh.",
    "Plum" => "A small, sweet fruit with a juicy flesh and a smooth skin.",
    "Rambutan" => "A tropical fruit with a hairy, red skin and a sweet, juicy flesh with a large seed.",
    "Tangerine" => "A small, juicy citrus fruit with a bright orange skin and a sweet, tangy flavor.",
    "Watermelon" => "A large, juicy melon with a green skin and a sweet, watery flesh.",
    'Umbu' => 'Umbu is a tropical fruit that is native to Brazil. It has a tangy, slightly sour taste and is often used to make juice or ice cream. Umbu is rich in vitamin C, potassium, and calcium, and also contains antioxidants that may help protect against disease. It is a popular fruit in Brazil and is enjoyed both fresh and cooked.'
];
