<?php

return
    [
        'Cashews' => 'Cashews are kidney-shaped nuts that are rich in protein, healthy fats, and a variety of vitamins and minerals.',
        'Pistachios' => 'Pistachios are small, greenish nuts that are a good source of fiber, protein, and healthy fats.',
        'Pecans' => 'Pecans are large, buttery nuts that are high in healthy unsaturated fats and antioxidants.',
        'Almonds' => 'Almonds are a nutrient-dense nut that is high in healthy monounsaturated fats, fiber, and protein.',
        'Macadamia Nuts' => 'Macadamia nuts are creamy, buttery nuts that are high in healthy fats, protein, and several important vitamins and minerals.',
        'Brazil nuts' => 'Brazil nuts are large, triangular-shaped nuts that are rich in selenium, magnesium, and healthy fats.',
        'Peanuts' => 'Peanuts are a legume that are high in protein, healthy fats, and a variety of vitamins and minerals.',
        'Walnuts' => 'Walnuts are a nutrient-dense nut that is high in healthy omega-3 fatty acids, antioxidants, and protein.',
        'Hazelnuts' => 'Hazelnuts are a nutrient-dense nut that is high in healthy unsaturated fats, fiber, and several important vitamins and minerals.',
        'Chestnuts' => 'Chestnuts are a starchy, low-fat nut that is high in fiber, vitamin C, and several important minerals.',
        'Pine Nuts' => 'Pine nuts are a small, delicate nut that is high in healthy fats, protein, and several important vitamins and minerals.',
        'Pili Nuts' => 'Pili nuts are a buttery, delicious nut that is high in healthy fats, protein, and several important vitamins and minerals.',
        'Kola Nuts' => 'Kola nuts are caffeine-rich nuts that are used to make soda and other caffeinated beverages.',
        'Saba Nuts' => 'Saba nuts, also known as sabanut or beniseed, are a type of seed that come from a tropical plant native to Africa. They are a good source of protein and healthy fats.',
        'Baru Nuts' => 'Baru nuts, also known as baru almonds or Brazilian almonds, are a type of nut that come from a tree native to Brazil. They are a good source of protein, fiber, and healthy fats.',
        'Hickory Nuts' => 'Hickory nuts are a type of nut that come from hickory trees, which are native to North America. They are a good source of protein and healthy fats, and have a rich, buttery flavor.',
        'Red Bopple Nuts' => 'Red bopple nuts, also known as Chinese hickory nuts or Chinese white nuts, are a type of nut that come from trees native to China. They are a good source of protein, fiber, and healthy fats, and have a sweet, buttery flavor.',
        'Tiger Nuts' => 'Tiger nuts, also known as chufa or earth almonds, are a type of tuber that grow in warm climates around the world. They are a good source of fiber and resistant starch, and have a sweet, nutty flavor.',
        'Mongongo Nuts' => 'Mongongo nuts, also known as manketti nuts or nongongo, are a type of nut that come from a tree native to southern Africa. They are a good source of protein, fiber, and healthy fats, and have a mild, nutty flavor.',
        'Cedar Nuts' => 'Cedar nuts, also known as Siberian pine nuts, are a type of nut that come from pine trees native to Russia and other parts of northern Europe and Asia. They are a good source of protein, fiber, and healthy fats, and have a sweet, buttery flavor.',
        'Bunya Nuts' => 'Bunya nuts are a type of nut that come from the bunya pine, a tree native to Australia. They are a good source of protein, fiber, and healthy fats, and have a starchy, nutty flavor.',
        'Candlenuts' => 'Candlenuts, also known as kukui nuts or candleberry nuts, are a type of nut that come from a tree native to Hawaii and other parts of the Pacific. They are a good source of healthy fats, and have a mild, nutty flavor.',
        'Ginkgo Nuts' => 'Ginkgo nuts are the seeds of the ginkgo biloba tree, which is native to China and other parts of Asia. They are a good source of protein and healthy fats, and have a nutty, slightly sweet flavor.',
        'Karuka Nuts' => 'Karuka nuts, also known as pangium edule or kepayang nuts, are a type of nut that come from a tree native to Southeast Asia and the Pacific. They are a good source of protein, fiber, and healthy fats, and have a slightly bitter, nutty flavor.',
        'Atherton Oak Nuts' => 'Atherton oak nuts, also known as Australian oak nuts or beef nuts, are a type of nut that come from a tree native to Australia. They are a good source of protein, fiber, and healthy fats, and have a rich, buttery flavor.',
        'Beech Nuts' => 'Beech Nuts are small, triangular nuts that grow on the American beech tree. They have a mild, sweet flavor and are high in protein and healthy fats. Beech nuts are often used as a substitute for coffee, as they can be roasted and ground to make a caffeine-free beverage. They can also be eaten raw, cooked, or processed into various products such as oil or butter.',
        'Butternuts' => 'Butternuts, also known as white walnuts, are the edible seeds of the Juglans cinerea tree, which is native to eastern North America. These elongated, light brown nuts have a rich, buttery flavor that is similar to that of macadamia nuts. They are high in healthy fats, protein, and fiber, and are a good source of minerals like magnesium and phosphorus. Butternuts can be eaten raw or roasted, and are often used in baking and confectionery.',
        "Mongongo nuts" => "The fruit of the mongongo tree, found in southern Africa.",
    ];
