<?php
return [
    'Cashews',
    'Pistachios',
    'Pecans',
    'Almonds',
    'Macadamia Nuts',
    'Brazil nuts',
    'Peanuts',
    'Walnuts',
    'Hazelnuts',
    'Chestnuts',
    'Pine Nuts',
    'Pili Nuts',
    'Kola Nuts',
    'Saba Nuts',
    'Baru Nuts',
    'Hickory Nuts',
    'Red Bopple Nuts',
    'Tiger Nuts',
    'Coconut',
    'Mongongo Nuts',
    'Cedar Nuts',
    'Bunya Nuts',
    'Candlenuts',
    'Ginkgo Nuts',
    'Karuka Nuts',
    'Atherton Oak Nuts',
    'Beech Nuts',
    'Butternuts',
];
