<?php
return [
    'Flax Seeds',
    'Chia Seeds',
    'Rajgira Seeds',
    'Sunflower Seeds',
    'Pumpkin Seeds',
    'Basil Seeds',
    'Hemp Seeds',
    'Pomegranate Seeds',
    'Apricot Kernels',
    'Sesame Seeds',
    'Grape Seeds',
    'Caraway Seeds',
    'Mustard Seeds',
    'Watermelon seed',
    'Durian',
    'Poppy seed',
    'Egusi Seeds',
    'Jackfruit Seeds',
    'Lotus Seeds',
    'Nigella Seeds',
    'Caraway Seeds',
];
