<?php

return [
    'Artichoke' => 'A type of thistle with a fleshy edible bud that is typically boiled or steamed and served with butter or a sauce.',
    'Arugula' => 'A type of leafy green vegetable with a slightly peppery taste. It is often used in salads and other dishes.',
    'Asparagus' => 'A spring vegetable that is typically cooked by boiling or steaming. It is often served as a side dish or in salads.',
    'Pepper' => 'A type of vegetable that comes in many varieties and colors, including green, red, yellow, and orange. Peppers can be eaten raw or cooked and are often used in salads, stir-fries, and other dishes.',
    'Hot Pepper' => 'A spicy variety of pepper that is often used to add heat to dishes. Some popular types of hot peppers include jalapeño, habanero, and cayenne.',
    'Beetroot' => 'A root vegetable that is typically roasted or boiled and served as a side dish or in salads. It has a sweet, earthy flavor and deep red color.',
    'Bok Choy' => 'A type of Chinese cabbage with tender green leaves and white stalks. It is often used in stir-fries and other Asian dishes.',
    'Broccoli' => 'A green vegetable with tightly clustered buds on thick stalks. It is typically cooked by boiling or steaming and is often served as a side dish or in salads.',
    'Cabbage' => 'A leafy green or purple vegetable that is often used in salads, soups, and stir-fries. It can also be pickled or fermented to make sauerkraut or kimchi.',
    'Carrot' => 'A root vegetable that is typically eaten raw or cooked. It is often used in salads, soups, and stews.',
    'Celery' => 'A crunchy vegetable with long, pale green stalks. It is often eaten raw as a snack or in salads, and is also used as a flavoring in soups and stews.',
    'Chive' => 'A herb in the onion family that is often used to flavor dishes. It has thin, hollow green stems and a mild onion-like taste.',
    'Radish' => 'A root vegetable with a crisp, peppery flavor. It is often eaten raw in salads, and can also be pickled or cooked in stir-fries and soups.',
    'Eggplant' => 'A vegetable with a glossy purple skin and white flesh. It is often used in Mediterranean and Middle Eastern dishes, and can be roasted, grilled, or fried.',
    'Garlic' => 'A bulbous plant in the onion family that is used for its pungent flavor and aroma. It is often used as a seasoning in dishes, and can also be roasted or used to make garlic bread.',
    'Onion' => 'A bulbous vegetable with a pungent flavor that is often used as a seasoning in dishes. It can be eaten raw or cooked, and is also used to make onion rings, soup, and other dishes.',
    'Red Onion' => 'A type of onion with a red or purple skin and a mild, sweet flavor. It is often used in salads and other dishes for its color and flavor.',
    'Jicama' => 'A root vegetable with a crunchy texture and slightly sweet flavor. It is often eaten raw in salads or as a snack.',
    'Kale' => 'Kale is a leafy green vegetable that is rich in nutrients such as vitamin C, vitamin K, and calcium. It has a slightly bitter taste and is often used in salads, smoothies, and soups.',
    'Kohlrabi' => 'Kohlrabi is a vegetable that is part of the cabbage family. It has a bulbous stem that tastes similar to broccoli stems or cabbage hearts. It can be eaten raw or cooked and is often used in salads or roasted as a side dish.',
    'Lettuce' => 'Lettuce is a leafy green vegetable that is often used in salads. It is low in calories and high in nutrients such as vitamin A, vitamin C, and folate. There are many different varieties of lettuce, including romaine, arugula, and iceberg.',
    'Okra' => 'Okra is a green vegetable that is often used in southern cooking. It has a mild flavor and a sticky texture that can be off-putting to some. Okra is high in vitamin C and fiber and can be prepared in a variety of ways, including frying, grilling, or stewing.',
    'Parsnip' => 'Parsnip is a root vegetable that looks like a white carrot. It has a sweet, nutty flavor and is often used in soups, stews, and roasted vegetable dishes. Parsnips are high in fiber, vitamin C, and potassium.',
    'Potatoes' => 'Potatoes are a starchy vegetable that is high in vitamin C and potassium. They come in many different varieties, including russet, red, and sweet potatoes. Potatoes are often boiled, mashed, roasted, or fried and are a staple in many cuisines around the world.',
    'Pumpkin' => 'Pumpkin is a winter squash that is often used in pies, soups, and baked goods. It is high in vitamin A, fiber, and potassium. Pumpkins come in many different varieties and can be cooked in a variety of ways, including roasting, baking, or boiling.',
    'Radicchio' => 'Radicchio is a type of chicory that is often used in salads. It has a bitter taste and a bright purple-red color. Radicchio is high in vitamin K and can be grilled or roasted as a side dish.',
    'Rutabaga' => 'Rutabaga is a root vegetable that is similar to a turnip. It has a sweet, nutty flavor and is often used in soups, stews, and roasted vegetable dishes. Rutabagas are high in vitamin C, fiber, and potassium.',
    'Shallot' => 'Shallots are a type of onion that have a milder, sweeter flavor than regular onions. They are often used in French cuisine and can be sautéed, roasted, or pickled. Shallots are high in vitamin C and can be a flavorful addition to many dishes.',
    'Spinach' => 'Spinach is a leafy green vegetable that is high in nutrients such as vitamin A, vitamin C, and iron. It has a mild, slightly bitter taste and can be eaten raw or cooked. Spinach is often used in salads, soups, and side dishes.',
    'Tomatoes' => 'Tomatoes are a fruit that is often used as a vegetable in cooking. They come in many different varieties, including cherry, roma, and heirloom tomatoes. Tomatoes are high in vitamin C and lycopene and are a staple ingredient in many dishes around the world.',
    'Turnips' => 'A root vegetable commonly used in stews and soups.',
    'Watercress' => 'A leafy green vegetable with a peppery taste, often used in salads.',
    'Zucchini' => 'A summer squash that is commonly used in Mediterranean cuisine.',
    'Cucumber' => 'A long, green-skinned vegetable often used in salads or pickled.',
    'Squash' => 'A type of vegetable that includes various winter and summer squash varieties.',
    'Scallop' => 'A type of shellfish that is often pan-seared and served as a seafood dish.',
];
