<?php
return [
    'Artichoke',
    'Arugula',
    'Asparagus',
    'Pepper',
    'Hot Pepper',
    'Beetroot',
    'Bok Choy',
    'Broccoli',
    'Cabbage',
    'Carrot',
    'Celery',
    'Chive',
    'Radish',
    'Eggplant',
    'Garlic',
    'Onion',
    'Red Onion',
    'Jicama',
    'Kale',
    'Kohlrabi',
    'Lettuce',
    'Okra',
    'Parsnip',
    'Potatoes',
    'Pumpkin',
    'Radicchio',
    'Rutabaga',
    'Shallot',
    'Spinach',
    'Tomatoes',
    'Turnips',
    'Watercress',
    'Zucchini',
    'Cucumber',
    'Squash',
    'Scallop',
];
